---
abstract: 'Interacts with ISC DHCPd'
author:
  - 'Jan Henning Thorsen'
build_requires:
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ISC-DHCPd
no_index:
  directory:
    - inc
    - t
requires:
  File::Path: 0
  Moose: 0
  NetAddr::IP: 0
version: 0.01
