---
abstract: 'Interacts with ISC DHCPd'
author:
  - 'Jan Henning Thorsen, all rights reserved.'
build_requires:
  Benchmark: 1
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.9
  Time::Local: 1.18
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ISC-DHCPd
no_index:
  directory:
    - example
    - inc
    - t
requires:
  File::Temp: 0.2
  IO::Pty: 1
  Moose: 0.9
  MooseX::Types: 0.12
  MooseX::Types::Path::Class: 0.05
  NetAddr::IP: 4
  POE::Filter::DHCPd::Lease: 0.04
  Path::Class: 0.19
  Time::HiRes: 1.9
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-ISC-DHCPd
  homepage: http://search.cpan.org/dist/Net-ISC-DHCPd
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/net-isc-dhcpd.git
version: 0.14
