---
abstract: 'Interacts with ISC DHCPd'
author:
  - 'Jan Henning Thorsen, all rights reserved.'
build_requires:
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ISC-DHCPd
no_index:
  directory:
    - inc
    - t
requires:
  File::Path: 2
  Moose: 0.8
  NetAddr::IP: 4
  POE::Filter::DHCPd::Lease: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
