---
abstract: 'Interacts with ISC DHCPd'
author:
  - 'Jan Henning Thorsen, all rights reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Pod: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ISC-DHCPd
no_index:
  directory:
    - inc
    - t
requires:
  File::Path: 2
  IO::Pty: 1
  Moose: 0.8
  MooseX::Types: 0.1
  NetAddr::IP: 4
  POE::Filter::DHCPd::Lease: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
